<?php 
	$page = "naslovna";
?>

<!doctype html>


<html lang="sr" class="no-js">

<head>
	<title>Savet za koordinaciju poslova bezbednosti saobraćaja na putevima na teritoriji Grada Novog Sada</title>

	<meta charset="utf-8">

	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta name="description" content="Savet za koordinaciju poslova bezbednosti saobraćaja na putevima na teritoriji Grada Novog Sada je osnovan od strane Grаdskоg vеća Grаdа Nоvоg Sаdа kao rаdnо tеlо čiji je jedan od zadataka da ostvaruje saradnju sa organima i organizacijama iz oblasti bezbednosti saobraćaja i usklađuje poslove u funkciji unapređenja bezbednosti saobraćaja na putevima na teritoriji Grada Novog Sada." />

	<link rel="shortcut icon" href="images/novisad_favicon.ico" type="image/x-icon">

	<link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/magnific-popup.css" media="screen">	
	<link rel="stylesheet" type="text/css" href="css/jquery.bxslider.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/owl.carousel.css" media="screen">
    <link rel="stylesheet" type="text/css" href="css/owl.theme.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/icomoon.css" media="screen">
	<link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">
    <!-- REVOLUTION BANNER CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

	
	<script type="text/javascript" src="js/jquery.min.js"></script>
	<script type="text/javascript" src="js/jquery.migrate.js"></script>
	<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="js/jquery.bxslider.min.js"></script>
	<script type="text/javascript" src="js/jquery.appear.js"></script>
	<script type="text/javascript" src="js/jquery.countTo.js"></script>
	<script type="text/javascript" src="js/bootstrap.js"></script>
	<script type="text/javascript" src="js/jquery.imagesloaded.min.js"></script>
	<script type="text/javascript" src="js/jquery.colorbox.js"></script>
	
	<script type="text/javascript" src="js/plugins-scroll.js"></script>
	<script type="text/javascript" src="js/waypoint.min.js"></script>
    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="js/jquery.themepunch.tools.min.js"></script>
    <script type="text/javascript" src="js/jquery.themepunch.revolution.min.js"></script>
	<script type="text/javascript" src="js/jquery.mb.YTPlayer.js"></script>
	<link rel="stylesheet" type="text/css" href="css/YTPlayer.css" media="screen">
	<script type="text/javascript" src="js/script.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter_ignore_list_rs.js"></script>
	<script type="text/javascript" src="js/cyrlatconverter.js"></script>

	<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
	<script type="application/ld+json">
	{
	  "@context" : "http://schema.org",
	  "@type" : "LocalBusiness",
	  "name" : "Савет за координацију послова безбедности саобраћаја на путевима на територији Града Новог Сада",
	  "image" : "http://sbsns.rs/sr/images/logo/ns-logo.png",
	  "telephone" : [ "+381-(0)21-529-721", "+381-(0)21-4882-835" ],
	  "email" : "office@sbsns.rs",
	  "address" : {
	    "@type" : "PostalAddress",
	    "streetAddress" : "Жарка Зрењанина 2",
	    "addressLocality" : "Нови Сад",
	    "addressCountry" : "Србија"
	  },
	  "url" : "http://www.sbsns.rs/sr/"
	}
	</script>

</head>
<body class="CyrLatConvert">

	<!-- Preloader-->
	<div class="preloader">
		<!-- <h2>Savet za bezbednost saobraćaja</h2>
		<h3>Novi Sad</h3> -->
	</div>

	<!-- Container - dodati klasu active zbog ukidawa preloadera  -->
	<div id="container" class="header3">
		<header class="clearfix">
			<!-- Static navbar -->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="header-top-line">
					<div class="container">
						<div class="row">
							<div class="col-md-6 col-sm-7">
								<span><i class="icon-phone"></i> +381-(0)21-529-721</span>
								<span><i class="icon-phone"></i> +381-(0)21-4882-835</span>
								<span class="CyrLatIgnore"><i class="icon-envelope"></i> office@sbsns.rs</span>
							</div>
							<div class="col-md-6 col-sm-5">
								<div class="flags-section">
									<ul class="language-choose">
										<li><a href="#lat"><img src="images/flag/srb.png" alt=""><span>Latinica</span><i class="fa fa-angle-down"></i></a>
											<ul class="drop-languages">
												<li><a href="#cyr"><img src="images/flag/srb.png" alt=""><span>Ćirilica</span></a></li>
												<li><a href="#"><img src="images/flag/uk.png" alt=""><span>Engleski</span></a></li>
											</ul>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>	
				<?php include 'include/logo-baner.php' ?>
				<?php include 'include/meni.php' ?>
			</nav>
		</header>
		<!-- End Header -->

		<!-- slider 
			================================================== -->
		<div id="slider" class="slider1">
			<!--
			#################################
				- THEMEPUNCH BANNER -
			#################################
			-->
			<div class="tp-banner-container">
				<div class="tp-banner" >
					<ul>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="upload/slide/01a.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="20% 30%" data-bgrepeat="no-repeat">
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Vredi li života?
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div>
							
							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="vredi-li-zivota.php" class="btn btn-primary">Saznajte više</a>
							</div>

							
						</li>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="upload/slide/01b.jpg"  alt="slidebg1b"  data-bgfit="cover" data-bgposition="0% 50%" data-bgrepeat="no-repeat">
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<!-- <div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Vredi li života?
							</div> -->
							
							<!-- LAYER NR. 2 -->
							<!-- <div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">
							</div> -->
							
							<!-- LAYER NR. 3 -->
							<!-- <div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="280"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="vredi-li-zivota.php" class="btn btn-primary">Saznajte više</a>
							</div> -->

							
						</li>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="upload/slide/02.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="0% 30%" data-bgrepeat="no-repeat">
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout text-center"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kiša menja sve!
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Prilagodi vožnju vremenskim prilikama. 
							</div>

							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kisa-menja-sve.php" class="btn btn-primary">Pročitajte više</a>
							</div>

							
						</li>
						<!-- SLIDE  -->
						<li data-transition="fade" data-slotamount="7" data-masterspeed="500" >
							<!-- MAIN IMAGE -->
							<img src="upload/slide/03.jpg"  alt="slidebg1"  data-bgfit="cover" data-bgposition="O% 30%" data-bgrepeat="no-repeat">
							<!-- LAYERS -->

							<!-- LAYER NR. 1 -->
							<div class="tp-caption lft large_bold_white customout"
								data-x="0"
								data-y="180"
								data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
								data-speed="700"
								data-start="1200"
								data-easing="Back.easeOut"
								data-endspeed="500"
								data-endeasing="Power4.easeIn"
								data-captionhidden="on"
								style="z-index: 4">Kad pijem ne vozim!
							</div>
							
							<!-- LAYER NR. 2 -->
							<div class="tp-caption lfl medium_thin_grey"
								data-x="0"
								data-y="260"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="1600"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14">Koliko te košta sledeće piće? 
							</div>

							<!-- LAYER NR. 3 -->
							<div class="tp-caption lfb medium_thin_grey"
								data-x="0"
								data-y="340"
								data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
								data-speed="1000"
								data-start="2000"
								data-easing="Back.easeInOut"
								data-endspeed="400"
								data-endeasing="Back.easeIn"
								style="z-index: 14"><a href="kad-pijem-ne-vozim.php" class="btn btn-primary">Saznajte više</a>
							</div>

							
						</li>
					</ul>
					<div class="tp-bannertimer"></div>
				</div>
			</div>
		</div>
		<!-- End slider -->

		<!-- content 
			================================================== -->
		<div id="content">

			<!-- services-section
				================================================== -->
			<div class="section-content services-section">

				<div class="services-box1">
					<div class="container">
						<div class="row">

							<?php
							    $number = 3;
							    $template = "savet1";
							    $category = "1";
							    $PHP_SELF = 'vesti.php';
							    include("/home/uprava/public_html/sbsns.rs/cnews/show_news.php");
							?>

						</div>
					</div>
				</div>

				<!-- banner-text2-section
					================================================== -->
				<div class="section-content jos-vesti bord-bottom">
					<div class="container">
						<h1><a href="arhiva.php">Ostale vesti</a></h1>					
					</div>
				</div>

			</div>

			<!-- about-section
				================================================== -->
			<div class="section-content about-section bord-bottom">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="jos-onama about-content triggerAnimation animated" data-animate="fadeInRight">
								<h1>O nama, ko smo i šta radimo</h1>
								<p>Savet za koordinaciju poslova bezbednosti saobraćaja na putevima na teritoriji Grada Novog Sada je od strane Grаdskоg vеća Grаdа Nоvоg Sаdа, u јаnuаru 2010., osnovano kao rаdnо tеlо Grаdskоg vеćа Grаdа Nоvоg Sаdа.</p>
								<p>Jedan od zadataka Saveta je da ostvaruje saradnju sa organima i organizacijama iz oblasti bezbednosti saobraćaja i usklađuje poslove u funkciji unapređenja bezbednosti saobraćaja na putevima na teritoriji Grada Novog Sada.</p>
								<p>Ostale podatke o Savetu pročitajte na stranici "O nama".</p>
								<h1><a href="onama.php">Saznajte više...</a></h1>
							</div>
						</div>
					</div>
				</div>
			</div>

			
			<!-- partners-section
				================================================== -->
			<div class="section-content team-section">
				<!-- <div class="title-section title2">
					<div class="container triggerAnimation animated" data-animate="bounceIn">
						<h1>Kratak naslov</h1>
						<p>Kratak tekst ko su ova preduzeća i zašto se linkovi ka njihovim veb stranicama nalaze ovde </p>
					</div>
				</div> -->
				<div class="team-box2">
					<div class="container">
						<div class="row">
							<div class="col-md-4">
								<div class="team-post">
									<a href="http://www.gspns.rs/"><img alt="" src="images/logo/jgspns-logo.png"></a>
									<div class="team-content">
										<h2>Javno gradsko saobraćajno preduzeće - Novi Sad</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<p>ЈGSP Nоvi Sаd је prеduzеćе kоје је nizоm dugоrоčnih оprеdеljеnjа usrеdsrеđеnо nа svаkоdnеvnо pоbоljšаnjе kvаlitеtа prеvоzа putnikа u grаdskоm, prigrаdskоm i mеđumеsnоm sаоbrаćајu</p>
										<ul class="team-social">
											<li><a class="world" href="http://www.gspns.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="https://www.facebook.com/JgspNoviSad" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="https://twitter.com/JGSPNoviSad" target="_blank"><i class="icon-twitter"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="team-post">
									<a href="http://www.jkpput.rs/"><img alt="" src="images/logo/jkp-put-logo.png"></a>
									<div class="team-content">
										<h2>Јаvnо kоmunаlnо prеduzеćе "PUТ" Nоvi Sаd</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<p>Јаvnо kоmunаlnо prеduzеćе "PUТ" Nоvi Sаd оsnоvао је Grаd Nоvi Sаd zа  pоtrеbе izgrаdnjе i оdržаvаnjа putеvа i ulicа nа tеritоriјi  Nоvоg Sаdа i prigrаdskih nаsеljа.</p>
										<ul class="team-social">
											<li><a class="world" href="http://www.jkpput.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<li><a class="facebook" href="https://www.facebook.com/jkpput/" target="_blank"><i class="icon-facebook"></i></a></li>
											<!-- <li><a class="twitter" href="#" target="_blank"><i class="icon-twitter"></i></a></li> -->
										</ul>
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<div class="team-post">
									<a href="http://www.parkingns.rs/"><img alt="" src="images/logo/parking-servis-ns-logo.png"></a>
									<div class="team-content">
										<h2>Javno komunalno preduzeće "Parking servis" Novi Sad</h2>
										<!-- <span>Podnaslov ako ga ima</span> -->
										<p>Dеlаtnоst prеduzеćа je оdržаvаnjе, urеđеnjе i kоrišćеnjе pаrkingа i јаvnih gаrаžа, kао i uslugе drumskоg sаоbrаćаја.</p>
										<ul class="team-social">
											<li><a class="world" href="http://www.parkingns.rs/" target="_blank"><i class="icon-world"></i></a></li>
											<!-- <li><a class="facebook" href="#" target="_blank"><i class="icon-facebook"></i></a></li>
											<li><a class="twitter" href="#" target="_blank"><i class="icon-twitter"></i></a></li> -->
										</ul>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- brzi-linkovi-section
				================================================== -->
			<div class="section-content team-section2">
				<div class="title-section title2">
					<div class="container triggerAnimation animated bounceIn" data-animate="bounceIn">
						<!-- <h1>Meet Our Professional Team</h1> -->
					</div>
				</div>
				<div class="team-box1">
					<div class="container">
						<div class="row">
							<div class="col-md-4">
								<div class="team-post triggerAnimation animated" data-animate="fadeInLeft">
									<img alt="" src="images/brzilink/odluka.jpg">
									<div class="team-content">
										<h2>Gradske odluke</h2>
										<span>Novi Sad</span>
										<p>Pogledajte važeće gradske odluke iz razlčitih oblasti koje se odnose na rad saveta i ostalih radnih tela.</p>
										<a href="odluke.php">Pogledajte <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
										<!-- <ul class="team-social">
											<li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a class="dribble" href="#"><i class="fa fa-dribbble"></i></a></li>
											<li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
										</ul> -->
									</div>
								</div>
								<div class="podnaziv"><h2>Gradske odluke</h2></div>
							</div>
							<div class="col-md-4">
								<div class="team-post triggerAnimation animated" data-animate="fadeInUp">
									<img alt="" src="images/brzilink/sastanak-ok.jpg">
									<div class="team-content">
										<h2>Sednice Saveta</h2>
										<span>Novi Sad</span>
										<p>Pogledajte zapisnike sa održanih sednica Saveta i ostalih radnih grupa.</p>
										<a href="sednice.php">Pogledajte <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
									</div>
								</div>
								<div class="podnaziv"><h2>Sednice Saveta</h2></div>
							</div>
							<div class="col-md-4">
								<div class="team-post triggerAnimation animated" data-animate="fadeInRight">
									<img alt="" src="images/brzilink/potvrda.jpg">
									<div class="team-content">
										<h2>Potvrde i zahtevi</h2>
										<span>Novi Sad</span>
										<p>Uputstva za podnošenje različitih zahteva radi dobijanja potvrda, uverenja i rešenja.</p>
										<a href="zahtevi.php">Pogledajte <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
									</div>
								</div>
								<div class="podnaziv"><h2>Potvrde i zahtevi</h2></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Popup bootstrap Modal -->
	<!-- Modal -->
	<div id="indexModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">

	    <!-- Modal content-->
	    <div class="modal-content">
	      <div class="modal-gore">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	      </div>
	      <div class="modal-body">
	        <div class="dugme">
	        	<a href="sbsnsdb/clanstvo.php#registracija" class="btnmodal btn-modal active">REGISTRACIJA</a>
	        </div>
	        <div class="modal-tekst">
	        	<p>Rеgistrаciјоm nа оvај sајt dоbiјаtе mоgućnоst dа nа Vаšu mејl аdrеsu primаtе nајnоviје infоrmаciје vеzаnе zа sаоbrаćај u Nоvоm Sаdu i dа dаvаnjеm prеdlоgа učеstvuјеtе u krеirаnju idеја zа unаprеđеnjе sаоbrаćаја u nаšеm grаdu!</p>
	        </div>
	      </div>
	      <div class="modal-dole">
	      	<a href="sbsnsdb/clanstvo.php">Već imam svoj nalog!</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="sbsnsdb/clanstvo.php#registracija">Registrujte se!</a>
	      </div>
	    </div>

	  </div>
	</div>
		<!-- End content -->


		<!-- footer 
			================================================== -->
		<?php include 'include/footer.php' ?>
		<!-- End footer -->
	</div>
	<!-- End Container -->
	
	

	<!-- SLIDER REVOLUTION SCRIPT INITIALISATION -->
	<!-- LOOK THE DOCUMENTATION FOR MORE INFORMATIONS -->

	<script type="text/javascript">

		var revapi;

		jQuery(document).ready(function() {

			   revapi = jQuery('.tp-banner').revolution(
				{
					delay:12000,
					startwidth:1140,
					startheight:480,
					hideThumbs:10,
					fullWidth:"on",
					forceFullWidth:"on",
					onHoverStop:"on",
					navigationType:"none",
					soloArrowLeftHOffset:30,
					soloArrowRightHOffset:30
				});

		});

	</script>
	<!-- END REVOLUTION SLIDER -->

	<!-- Skripta za aktivaciju linkova #lat i #cyr -->
	<script>
		$.CyrLatConverter({
		  permalink_hash : "on"
		});
	</script>

<script>
	$.CyrLatConverter('L2C');
</script>

<!-- Prikazivanje modal prozora prilikom ucitavanja stranice sa kasnjenjem i prikaziivanje samo jedanput u sesiji, ako se prozor ili tab zatvori modal ce se ponovo pojaviti u novoj sesiji. Ako umest sessionStorage koristimo localStorage on traje neograniceno i modal se nece pojavljivati na lokalnom racunaru. -->
<script>
		$(document).ready(function(){
			var dialogShown = sessionStorage.getItem('dialogShown');
			if (!dialogShown)
			{
				setTimeout(function() {
			    $('#indexModal').modal();
				}, 3000);
				sessionStorage.setItem('dialogShown', 1)
			}
			else
			{
				$("#indexModal").hide();
			}
		});
	</script>
	
	
</body>

</html>